const donors = [
  {
    id: 1,
    firstName: "Rahul",
    lastName: "Sharma",
    bloodGroup: "A+",
    gender: "Male",
    age: 30,
    streetAddress: "101 MG Road, Ghaziabad",
  },
  {
    id: 2,
    firstName: "Anjali",
    lastName: "Kumar",
    bloodGroup: "B+",
    gender: "Female",
    age: 25,
    streetAddress: "202 Lake View, Ghaziabad",
  },
  {
    id: 3,
    firstName: "Vijay",
    lastName: "Reddy",
    bloodGroup: "AB+",
    gender: "Male",
    age: 34,
    streetAddress: "405 High Street, Ghaziabad",
  },
  {
    id: 4,
    firstName: "Sunita",
    lastName: "Patel",
    bloodGroup: "O-",
    gender: "Female",
    age: 29,
    streetAddress: "78 Sector 15, Ghaziabad",
  },
  {
    id: 5,
    firstName: "Manish",
    lastName: "Sinha",
    bloodGroup: "A-",
    gender: "Male",
    age: 42,
    streetAddress: "88 Gandhi Path, Ghaziabad",
  },
  {
    id: 6,
    firstName: "Kavita",
    lastName: "Mehta",
    bloodGroup: "B-",
    gender: "Female",
    age: 36,
    streetAddress: "12 Shanti Nagar, Ghaziabad",
  },
  {
    id: 7,
    firstName: "Amit",
    lastName: "Verma",
    bloodGroup: "AB-",
    gender: "Male",
    age: 31,
    streetAddress: "55 River Road, Ghaziabad",
  },
  {
    id: 8,
    firstName: "Deepa",
    lastName: "Gupta",
    bloodGroup: "O+",
    gender: "Female",
    age: 26,
    streetAddress: "140 Blossom Avenue, Ghaziabad",
  },
  {
    id: 9,
    firstName: "Harish",
    lastName: "Chopra",
    bloodGroup: "A+",
    gender: "Male",
    age: 39,
    streetAddress: "230 Azad Lane, Ghaziabad",
  },
  {
    id: 10,
    firstName: "Priya",
    lastName: "Rajput",
    bloodGroup: "B+",
    gender: "Female",
    age: 33,
    streetAddress: "67 Sunshine Apartments, Ghaziabad",
  },
];

export default donors;
